config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
  :registrations => 'users/registrations'
  }
  devise_scope :user do
    get 'create' => 'users/registrations#create'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  
  resources :conferencerooms, only: %i(new create index) do
  resources :users, only: %i(new create)
    resources :schedules, only: %i(new create)
  end
  
end

app/models/conferenceroom.rb
class Conferenceroom < ApplicationRecord
    belongs_to :facility
    has_many :schedules, dependent: :destroy
    
    accepts_nested_attributes_for :schedules
end

app/controllers/conferencerooms_controller.rb
class ConferenceroomsController < ApplicationController
  def new
    @conferenceroom = Conferenceroom.new
  end
  
  def create
    facility = Facility.new
    facility.save
    @conferenceroom = Conferenceroom.new(conferenceroom_params)
    @conferenceroom.facility_id = 1
    if @conferenceroom.save
      flash[:success] = "会議室を登録しました"
      redirect_to root_url
    else
      render 'new'
    end
  end
  
  def index
    @conferencerooms = Conferenceroom.limit(10).includes(:schedules, :facility).order('created_at DESC')
  end
  
  private
    def conferenceroom_params
      params.require(:conferenceroom).permit(:people, :price, :availabletime, :remarks)
    end
end

app/helpers/conferencerooms_helper.rb
module ConferenceroomsHelper
end

app/views/conferencerooms/index.html.erb
<div class="container-hluid">
  <div class="row no-gutters">
    <div class="col-3 bg-primary ">
      <h1>test</h1>
      <h1>test</h1>
      <h1>test</h1>
    </div>
    <div class="col-9">
      <hr>
      <br>
    <h1>会議室一覧</h1>
    <div>
        <%= link_to "新規登録", new_conferenceroom_path, class: "btn btn-primary" %>
    </div>
    <br>
 ------------------------------
    <table class="table table-bordered">
      <thead>
        <tr>
          <th scope="col">会議室名</th>
          <th scope="col">収容人数</th>
          <th scope="col">利用金額</th>
          <th scope="col">使用可能時間</th>
        </tr>
      </thead>
      <tbody>
        <% @conferencerooms.each do |conferenceroom| %>
          <tr>
            <th scope="row"><%= "第　#{i+1} 会議室" %></th>
            <td><%= conferenceroom.people %></td>
            <td><%= conferenceroom.price %></td>
            <td><%= conferenceroom.starttime + "~" + conferenceroom.endtime %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    ---------------------------------
    </div>
  </div>
</div>

app/views/conferencerooms/new.html.erb
<div class="container-hluid">
  <div class="row no-gutters">
    <div class="col-3 bg-primary ">
      <h1>test</h1>
      <h1>test</h1>
      <h1>test</h1>
    </div>
    <div class="col-9">
      <hr>
      <br>
    <h1>会議室の新規登録</h1>
    <br>
 
    <div class="border col-5">
        <br>
        <div class="row">
          <%= form_with model: @conferenceroom do |f| %>
          　<%= f.label :people %>
              <%= f.text_field :people %>
              
              <%= f.label :price %>
              <%= f.text_field :price %>
              
              <%= f.label :starttime %>
              <%= f.text_field :starttime %>
              
              <%= f.label :endtime %>
              <%= f.text_field :endtime %>
              
              <%= f.label :remarks %>
              <%= f.text_field :remarks %>
              
              <%= f.submit "登録", class: "btn btn-primary" %>
            <% end %>
        </div>
    </div>
    </div>
  </div>
</div>